[package]
name = "fh"
version = "0.1.2"
authors = ["Determinate Systems <hello@determinate.systems>"]
edition = "2021"
license = "Apache 2.0"

[dependencies]
async-trait = "0.1.73"
clap = { version = "4.3.2", default-features = false, features = [
  "color",
  "derive",
  "env",
  "help",
  "std",
] }
color-eyre = "0.6.2"
indicatif = { version = "0.17.6", default-features = false }
lazy_static = "1.4.0"
nixel = "5.2.0"
prettytable-rs = "0.10.0"
reqwest = { version = "0.11", default-features = false, features = [
  "json",
  "rustls-tls",
] }
thiserror = { version = "1.0.44", default-features = false }
tokio = { version = "1.30.0", default-features = false, features = [
  "fs",
  "macros",
  "rt-multi-thread",
] }
semver = { version = "1.0.18", features = ["serde"] }
serde = "1.0.188"
serde_derive = "1.0.188"
url = { version = "2.4.0", features = ["serde"] }
regex = "1.9.4"
tracing-error = "0.2.0"
tracing-subscriber = { version = "0.3.17", features = ["env-filter", "json"] }
tracing = "0.1.37"
