name: Build fh artifacts

on:
  pull_request:
  push:
    branches: [main]

jobs:
  build-artifacts-X64-macOS:
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v3

      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main

      - name: Build package
        run: |
          nix build .# -L

  build-artifacts-X64-Linux:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main

      - name: Build package
        run: |
          nix build .# -L
