name: Rust checks

on:
  pull_request:
  push:
    branches: [main]

jobs:
  rust-fmt-and-clippy:
    runs-on: UbuntuLatest32Cores128G
    steps:
      - uses: actions/checkout@v4

      - uses: DeterminateSystems/nix-installer-action@v4
        with:
          determinate: true

      - uses: DeterminateSystems/flakehub-cache-action@main

      - name: Rust formatting
        run: nix develop --command cargo fmt --check

      - name: Clippy
        run: nix develop --command cargo clippy --all-targets --all-features --  -Dwarnings

      - name: Test
        run: nix develop --command cargo test --all-features
